### ISSUE TITLE
Choose one of those UI Components Library

### ISSUE THREAD

**Issue by Dv-Joan** [Dv-Joan/expense-tracker#13]
Mobile Components  Library 

1. **RN Elements** : [https://reactnativeelements.com/](url)
2.  **Nativebase** : [https://docs.nativebase.io/](url)
3. **Shoutem** : [https://shoutem.github.io/docs/ui-toolkit/components/](url)
4. **RN Paper** : [https://callstack.github.io/react-native-paper/docs/components](url)

Check out the docs and choose one of those @MiguelRequenaR

**Comment by Dv-Joan** [comment]
Take this issue seriously because we don't want to regret it

**Comment by MiguelRequenaR** [comment]
we are ready

**Comment by MiguelRequenaR** [comment]
choose https://docs.nativebase.io/

**Comment by Dv-Joan** [comment]
Nativebase
